### PR TITLE
Ignore hash part of the URL

### PR DESCRIPTION
**Pull request by michaelwinser**
This is particularly important for Google Docs urls but also helps with a bunch of other sites and single page apps.

### CODE REVIEW

**Comment by joeyAghion** [comment]
Hey @michaelwinser. Thanks for using this!

As I see it, there are at least 3 degrees of hash fragment usage:
1. Basic scrolling to a page anchor. (I agree that these can be closed as duplicates.)
2. Significant page state changes such as viewing different sheets in a Google spreadsheet. (Debatable.)
3. Sites that render _all_ of their "pages" within hash fragments. (Locations that share base URLs should _not_ be closed as duplicates.)

There used to be lots of sites in the 3rd category (Twitter, Gawker, many Google apps), so I had intentionally chosen the current approach. Now that I revisit it, I can't think of notable sites that still operate this way, so this might be an OK change.

Let's try it.

**Comment by joeyAghion** [comment]
Mind just removing the `console.log` before I merge?

**Comment by michaelwinser** [comment]
I had thought about having a whitelist  / blacklist or even a global option but like you I couldn't find any meaningful sites that still use the hash as state. I have some unfinished edits to explore these options but I'll wait until it's a problem.

Great extension BTW. It has definitely helped.

**Comment by joeyAghion** [comment]
I just release v0.6 to the Chrome web store. You can force an upgrade by going to chrome://extensions, checking _developer mode_ and clicking _update extensions now_.

**Pull request merged**
